### ISSUE TITLE
[solved] folder being renamed to "-ar-24_163300" (date is 31 march 2024)

### ISSUE THREAD

**Issue by dontreadme** [ksavage/save-backup#1]
how can i fix this? im using the DD-MMM-YY format

**Comment by ksavage** [comment]
Can you paste your file? I need to see what your doing for that to happen :)

**Comment by dontreadme** [comment]
[New Text Document.txt](https://github.com/ksavage/save-backup/files/14816912/New.Text.Document.txt)

i only changed where i want the savefiles to be saved

**Comment by ksavage** [comment]
[Try-This.txt](https://github.com/ksavage/save-backup/files/14817124/Try-This.txt)

Give this one a go and let me know how it goes.
